# MDMC cron job will push new documentation to ci branch in this repo
# whenever the documentation has changed.
# This job complement this by automatically creating a PR ready to 
# merged by a human into master, and with appropriate instructions

name: Create pull request

on:
  push:
    branches:
    - ci

jobs:
  pull_request:
    name: Pull request
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "master"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: "CI doc deployment"
          pr_body: "An automated PR to push new changes to the documentation. When merging, please do not delete the `ci` branch, as the Github Actions script needs an upstream to push to."
